apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-rest-crud
  template:
    metadata:
      labels:
        app: go-rest-crud
    spec:
      containers:
      - name: hello-py
        image: dharlequin/go-rest-crud:v4
        env:
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: hello-secret
                key: DB_HOST
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: hello-secret
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: hello-secret
                key: DB_PASSWORD
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: hello-secret
                key: DB_NAME
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: hello-secret
                key: DB_PORT
        ports:
        - name: web
          containerPort: 8080
