apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/auth-url: "http://auth.auth.svc.cluster.local:9000/auth"
    nginx.ingress.kubernetes.io/auth-response-headers: "X-User,X-Email,X-UserId"
spec:
  rules:
  - host: arch.homework
    http:
      paths:
        - path: /myapp($|/)(.*)
          pathType: Prefix
          backend:
            service:
              name: app-service
              port:
                number: 9000
